### ISSUE TITLE
Joining clan does not work

### ISSUE THREAD

**Issue by Nojoke185** [FAForever/clans#25]
Non clan member tries to join a clan - join clan button is disabled and does not respond

comment from Sheeo:

clans system is malfunctioning at the moment 
Specifically joining clans is not working for some reason
I’ll need to check it out
![capture](https://cloud.githubusercontent.com/assets/16309355/13934644/1c8265ce-efab-11e5-9e23-f76761fa863f.JPG)

**Comment by speed2CZ** [comment]
From what I've seen in last months, the only way to join clan was on this page, clicking on join clan, then leader has to accept you. No other way worked.

**Comment by IDragonfire** [comment]
Did you try this way?

![image](https://cloud.githubusercontent.com/assets/1217999/15242346/0765227a-18f6-11e6-8619-2d8a7e894517.png)

**Comment by speed2CZ** [comment]
I can do that but the person didnt get any invitation or at least didnt find any, nothing in notifications, my clan page empty, is it somewhere esle or?

**Comment by speed2CZ** [comment]
http://postimg.org/image/czg0yl2m9/
clicking the send button did nothing

**Comment by IDragonfire** [comment]
@speed2CZ  Is the player already in a clan?

**Comment by IDragonfire** [comment]
> I can do that but the person didnt get any invitation or at least didnt find any, nothing in notifications, my clan page empty, is it somewhere esle or?

They should get an invitation, if correctly in the notification tab ...

**Comment by IDragonfire** [comment]
btw.

> Non clan member tries to join a clan - join clan button is disabled and does not respond

THIS IS CORRECT !
You cannot "Join a clan" if you are allready in a clan ;)

**Comment by Nojoke185** [comment]
this wasn't for me :) it was for a new member (not already in a clan)

**Comment by IDragonfire** [comment]
Without the database I cannot test it, because locally it is working ..

**Comment by IDragonfire** [comment]
Found the problem ...
somehow the database schema was not transferred correctly ...

```sql
ALTER TABLE `fafclans`.`clan_invites` 
CHANGE COLUMN `user_request` `user_request` INT(11) NOT NULL DEFAULT 0 COMMENT '' ;
```

**Comment by Sheeo** [comment]
The migration has been run in production -- can you confirm this works now?

**Comment by IDragonfire** [comment]
fixed
