### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/clans#26]
I go to clan page, slick on log in, the the small "window" that pops out from it I type in my name and passwork, click on log in and nothing happens. I have to reload page and Im logged in.

**Comment by IDragonfire** [comment]
I bet it is because the domain moved from `faforever.com/clans` to `http://clans.faforever.com/` OR we have no `http` in front of it anymore ...

**Comment by axel1200** [comment]
Yeah it did want to open the same issue... it is quite painfull :#... Took me half an hour to figure out it was the WebApp and not the client opening it (probably becuase I'm an idiot)

**Comment by brendanjhart** [comment]
HI Dragonfire,

I am thebeej...  Nice work to finish the application!

I can take a look at this issue if you are busy. Is there a test server access?

**Comment by IDragonfire** [comment]
New API used oauth .. this is then obsolete ...
