### ISSUE TITLE
git URL confusing

### ISSUE THREAD

**Issue by Arifi** [FAForever/clans#32]
Hi FAF

When i try to clone this repo (the new clans) i got the code of the old clans repo
Any help ?

Thanks

**Comment by IDragonfire** [comment]
Git has The concept of branches 
Checkout The branch 'Feat/react'

**Comment by IDragonfire** [comment]
A good tutorial 
https://de.atlassian.com/git/tutorials/using-branches/

**Comment by Arifi** [comment]
Oh dude .. i thought it s another repo..
I know branches thx...

**Comment by Arifi** [comment]
They gave me the URL and didnt specify the branch... sorry

**Comment by IDragonfire** [comment]
Who gave you the url?

**Comment by Arifi** [comment]
Tokyto_
I'm going to help

**Comment by IDragonfire** [comment]
Thanks ;) Maybe it is a good idea to join slack

**Comment by Arifi** [comment]
Sure... last night voodoo was offline, so i still waiting the invite on slack

**Comment by IDragonfire** [comment]
Join slack ;)
http://slackinvite.faforever.com/

**Comment by Arifi** [comment]
ok im coming...
