### ISSUE TITLE
clan login leads to http://_ and 'Accept Request' is inactive (while Reject Request' is active)

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/clans#40]
2 bugs in one Issue:
1. I tried a login on http://clans.faforever.com/ .. lead me to http://_
(when I choose page back and reIoaded, I was logged in.)
2. I myClan I couldn't accept a Membership request, 'Accept request' is inactive (while Reject request' is active)

**Comment by IDragonfire** [comment]
Thank you very much, but the old app will be replaced, hopefully soon... 
https://clans.test.faforever.com/

**Comment by GrotheFAF** [comment]
why did you close it? is it fixed?

**Comment by IDragonfire** [comment]
I don't maintain the old clanapp, since the new clanapp is ready ....
https://clans.test.faforever.com/

**Comment by GrotheFAF** [comment]
well I can't login...
